# -*- coding: utf-8 -*-
"""panda_data_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Tb6cww6SDG-SebhF0V91mbGxcZ9AB5rK
"""

import pandas as pd
import json

datos = {
    "Nombre": ["Pepinillo Hernández", "Lúpulo de Dios", "Juan Juon", "Jimmy el Patatas", "Lorenzo Retaguardias"],
    "Cereal favorito": ["Korn Floks", "Verdurinis", "Zumbaritas", "Diabetukis, Papá", "Fibra Máxima 3000"],
    "Hora del desayuno": ["11:00", "07:30", "07:00", "08:30", "09:30"]
}

df = pd.DataFrame(datos)
df["Fruta que acompaña al cereal"]= pd.Series(["fresa","manzana","uvas","fresa","plátano"])

df_dropped=df.drop(columns=["Hora del desayuno"])

df_dropped

import pandas as pd
import json
datos_productos = {
    "nombre": ["Pokemaster", "Cegatron", "Pikame Mucho", "Lazarillo de Tormes", "Stevie Wonder", "Needle", "El AyMeDuele"],
    "precio": [10000, 5500, 3500, 750, 15500, 12250, 23000],
    "peso": [1.2, 1.5, 2.3, 5.5, 3.4, 2.4, 8.8],
    "capacidad de destrucción retinal": [3, 7, 6, 8, 9, 2, 10],
    "disponible": [True, False, True, True, False, False, True]
}

indice = [1, 2, 3, 4, 5, 6, 7]

df1=pd.DataFrame(datos_productos, index=[indice])
df1[["nombre","precio"]]


# Quiero un DataFrame que contenga los productos "Pikame Mucho" y "Stevie Wonder"
pm_lpt= df1.loc[[3,5]]
display(pm_lpt)

# Quiero un DataFrame que contenga desde el producto #4 hasta el último
p4_final =df1.loc[4:]
display(p4_final)

# Quiero un DataFrame que contenga desde el primer producto hasta el producto #5
primer_p5 = df1.loc[1:5]
display(primer_p5)

# Quiero un DataFrame que contenga los productos "Pikame Mucho" y "Lazarillo de Tormes", pero sólo con las columnas "nombre", "precio" y "peso"
pm_lt_pp = df1.loc[[3,4],["nombre","precio","peso"]]
display(pm_lt_pp)

# Quiero un DataFrame que contenga todos los productos pero con sólo las columnas 'nombre', 'precio' y 'capacidad de destrucción retinal'
t_pcdr = df1[["nombre","precio","capacidad de destrucción retinal"]]
display(t_pcdr)


# Quiero un DataFrame que contenga desde el producto #3 hasta el #6, pero sólo las columnas 'nombre', 'precio' y 'disponible'
p3_p6_pd = df1.loc[3:6,['nombre', 'precio', 'disponible']]
display(p3_p6_pd)

import pandas as pd
import json

file_jason = open("/content/drive/MyDrive/datasets_tc/new_york_times_bestsellers-clean.json", "r")
result_data= json.load(file_jason)
file_jason.close

df= pd.DataFrame.from_dict(result_data)
df.shape
df.head()
df.dtypes
#¿Qué podemos saber de este dataset con tan sólo leer el nombre del archivo y los nombres de las columnas?
#Que será un archivo con los datos de los libros más vendidos según el New York Times

#¿Cuál es el tamaño (forma) de nuestro DataFrame? ¿Podríamos considerarlo un dataset grande o pequeño?
#(3033,12) es un data set grande

#¿Crees que los nombres de las columnas son suficientemente descriptivos? ¿Podrían ser más claros o limpios?
#No todos, a partir del que dice "oid" todos empiezan a tener números raros que no se explica para qué son

#¿Qué tipos de datos tenemos?
#Integer y strings

#¿Qué significa el formato en el que tenemos las fechas?


#¿Qué tipo de preguntas podríamos responder usando los datos numéricos de este dataset?
#¿Qué tipo de preguntas podríamos responder usando los datos no-numéricos?